# Generated by Django 2.2.8 on 2020-01-24 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("defections", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="defection",
            options={
                "verbose_name": "Акт обнаружения брака",
                "verbose_name_plural": "Акты обнаружения брака",
            },
        ),
    ]
