# Generated by Django 3.0.2 on 2020-01-28 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipmentoffering'),
        ('defections', '0002_auto_20200124_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='defection',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defections', to='shipments.Shipment', verbose_name='Отгрузка'),
        ),
    ]
