# Generated by Django 3.0.2 on 2020-09-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offerings", "0004_sparepart"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparepart",
            name="height",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Высота, мм."
            ),
        ),
        migrations.AddField(
            model_name="sparepart",
            name="length",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Длина, мм."
            ),
        ),
        migrations.AddField(
            model_name="sparepart",
            name="mark",
            field=models.CharField(
                max_length=250, null=True, verbose_name="Маркировка"
            ),
        ),
        migrations.AddField(
            model_name="sparepart",
            name="width",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Ширина, мм."
            ),
        ),
    ]
