# Generated by Django 3.0.2 on 2020-10-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offerings", "0007_sparepart_primary_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sparepart",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=250, verbose_name="Описание"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sparepart",
            name="equipment",
            field=models.CharField(
                blank=True,
                default="",
                max_length=250,
                verbose_name="Совместимое оборудование",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sparepart",
            name="mark",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Маркировка"
            ),
        ),
        migrations.AlterField(
            model_name="sparepart",
            name="primary_image",
            field=models.FileField(
                blank=True, upload_to="galery/", verbose_name="Основной вид"
            ),
        ),
        migrations.AlterField(
            model_name="sparepart",
            name="tags",
            field=models.CharField(blank=True, max_length=250, verbose_name="Теги"),
        ),
    ]
