# Generated by Django 3.0.2 on 2020-10-01 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0010_auto_20201001_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePartImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.ImageField(upload_to='galery/')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='offerings.SparePart', verbose_name='Изображение')),
            ],
        ),
    ]
