# Generated by Django 3.0.2 on 2021-01-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('offerings', '0015_sparepart_aliexpress_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePartIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_code', models.CharField(db_index=True, max_length=36, null=True, verbose_name='Внешний код')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Integration', verbose_name='Интеграция')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='offerings.SparePart', verbose_name='Запасная часть')),
            ],
        ),
    ]
