# Generated by Django 3.0.2 on 2021-01-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0016_sparepartintegration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sparepartintegration',
            options={'ordering': ('integration',), 'verbose_name': 'Интеграция', 'verbose_name_plural': 'Интеграции'},
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='aliexpress_code',
        ),
    ]
