# Generated by Django 3.0.2 on 2021-01-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0017_auto_20210124_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
