# Generated by Django 3.0.2 on 2021-01-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Внешняя система')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Интеграция',
                'verbose_name_plural': 'Интеграции',
                'ordering': ('code',),
            },
        ),
    ]
