# Generated by Django 2.2.4 on 2019-11-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0003_auto_20191116_0018"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryprice",
            name="weight_from",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Вес от"
            ),
        ),
    ]
