# Generated by Django 2.2.4 on 2019-11-15 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_auto_20191116_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryprice',
            name='delivery_company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='logistics.DeliveryCompany', verbose_name='Транспортная компания'),
        ),
    ]
