# Generated by Django 2.2.4 on 2019-11-15 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_auto_20191116_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryprice',
            name='price_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='logistics.DeliveryPriceType', verbose_name='Тип тарифа'),
        ),
    ]
