# Generated by Django 2.2.4 on 2019-08-17 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttype',
            options={'ordering': ['name'], 'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
    ]
