# Generated by Django 2.2.4 on 2019-10-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190831_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttype',
            options={'ordering': ['name'], 'verbose_name': 'Тип контрагента', 'verbose_name_plural': 'Типы контрагентов'},
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Описание'),
        ),
    ]
