# Generated by Django 2.2.8 on 2020-01-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_legalentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='code_1c',
            field=models.CharField(db_index=True, max_length=9, verbose_name='Код в 1С'),
        ),
    ]
