# Generated by Django 3.0.2 on 2020-06-23 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='primary_legal_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_account', to='accounts.LegalEntity', verbose_name='Основное юр. лицо'),
        ),
    ]
