# Generated by Django 3.0.2 on 2021-01-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200626_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='name',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Название'),
        ),
    ]
