# Generated by Django 3.0.2 on 2020-02-17 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadChannell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Канал привлечения',
                'verbose_name_plural': 'Каналы привлечения',
                'ordering': ['updated'],
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Наименование')),
                ('secret_key', models.CharField(db_index=True, max_length=250, verbose_name='Секретный ключ')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Источник лида',
                'verbose_name_plural': 'Источники лидов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=20, verbose_name='КПП')),
                ('company_name', models.CharField(blank=True, max_length=250, verbose_name='Компания')),
                ('city', models.CharField(blank=True, max_length=250, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Адрес')),
                ('sale_channels', models.CharField(blank=True, max_length=250, verbose_name='Каналы продаж')),
                ('sale_regions', models.CharField(blank=True, max_length=250, verbose_name='Регионы присутствия')),
                ('sale_points', models.CharField(blank=True, max_length=250, verbose_name='Точки продаж')),
                ('web_address', models.CharField(blank=True, max_length=250, verbose_name='Адрес сайта')),
                ('comment', models.CharField(blank=True, max_length=250, verbose_name='Комментарий')),
                ('first_person', models.CharField(blank=True, max_length=250, verbose_name='ЛПР')),
                ('first_person_position', models.CharField(blank=True, max_length=250, verbose_name='Должность')),
                ('bank_account', models.CharField(blank=True, max_length=250, verbose_name='Р/С')),
                ('bank_name', models.CharField(blank=True, max_length=250, verbose_name='Банк')),
                ('bank_rcbic', models.CharField(blank=True, max_length=250, verbose_name='БИК')),
                ('bank_corr_account', models.CharField(blank=True, max_length=250, verbose_name='Корр. счет')),
                ('contact_person', models.CharField(blank=True, max_length=250, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(blank=True, max_length=250, verbose_name='Телефон для связи')),
                ('contact_email', models.CharField(blank=True, max_length=250, verbose_name='Email для связи')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('channell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.LeadChannell', verbose_name='Канал')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.LeadSource', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ['created'],
            },
        ),
    ]
