# Generated by Django 3.0.2 on 2020-02-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="channell",
            new_name="channel",
        ),
    ]
