# Generated by Django 3.0.2 on 2020-02-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_auto_20200218_2237"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LeadChannell",
            new_name="LeadChannel",
        ),
    ]
