# Generated by Django 3.0.2 on 2020-05-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_auto_20200218_2239"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="delete_mark",
            field=models.BooleanField(
                default=False, verbose_name="Пометка на удаление"
            ),
        ),
    ]
