# Generated by Django 3.0.2 on 2020-04-07 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_auto_20200407_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataseries',
            name='dataSource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series', to='metrics.DataSource', verbose_name='Источник'),
        ),
    ]
