# Generated by Django 3.0.2 on 2020-04-07 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_dataseries_datasource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataseries',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата'),
        ),
    ]
