# Generated by Django 3.0.2 on 2020-04-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_dayresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataseries',
            options={'ordering': ['-created'], 'verbose_name': 'Серия', 'verbose_name_plural': 'Серии'},
        ),
    ]
