# Generated by Django 3.0.2 on 2021-01-12 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('extid', models.CharField(db_index=True, max_length=36, verbose_name='Внешний код')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статус договора',
                'verbose_name_plural': 'Статусы договоров',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('extid', models.CharField(db_index=True, max_length=36, verbose_name='Внешний код')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип договора',
                'verbose_name_plural': 'Типы договоров',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contracts.ContractState', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='contract',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contracts.ContractType', verbose_name='Тип'),
        ),
    ]
