# Generated by Django 3.0.2 on 2021-01-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20210112_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractstate',
            name='extid',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, verbose_name='Внешний код'),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='extid',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, verbose_name='Внешний код'),
        ),
    ]
