# Generated by Django 2.2.4 on 2019-12-28 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.OrderState', verbose_name='Состояние'),
            preserve_default=False,
        ),
    ]
