# Generated by Django 2.2.8 on 2020-01-15 02:13

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_auto_20200115_1143"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=9,
                verbose_name="Сумма всего",
            ),
        ),
    ]
