# Generated by Django 3.0.2 on 2021-01-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderoffering_extid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Канал продаж',
                'verbose_name_plural': 'Каналы продаж',
                'ordering': ['name'],
            },
        ),
    ]
