# Generated by Django 3.0.2 on 2021-01-22 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.OrderChannel', verbose_name='Канал продаж'),
        ),
    ]
