# Generated by Django 2.2.4 on 2019-08-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommunicationType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tsid",
                    models.CharField(
                        blank=True, db_index=True, editable=False, max_length=36
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("code", models.CharField(max_length=6)),
                ("is_phone", models.BooleanField(default=False)),
            ],
        ),
    ]
