# Generated by Django 2.2.4 on 2019-08-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationtype',
            name='tsid',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
    ]
