# Generated by Django 2.2.4 on 2019-10-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_auto_20190827_2132"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="communicationtype",
            options={
                "ordering": ["name"],
                "verbose_name": "Тип средства связи",
                "verbose_name_plural": "Типы средств связи",
            },
        ),
    ]
